version: '2'
services:
  web:
    build: .
    command: npm run dev:backend
    volumes:
      - .:/usr/app/
    ports:
      - "3000:3000"
    depends_on:
      - rethink
  rethink:
    image: rethinkdb
    ports:
      - "38080:8080"
      - "38015:28015"
      - "39015:29015"
