version: '2'
services:
  web:
    build: .
    command: npm run dev
    volumes:
      - .:/usr/app/
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://iwashere@postgres/iwashere
  postgres:
    image: postgres:10
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: password
